### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by ghost** [browserify/discuss#1]
We should have one of these.

The js foundation has one https://js.foundation/community/code-of-conduct we could copy. I think it's also important that people understand the concepts and reasons.

Thoughts?

**Comment by calvinmetcalf** [comment]
node, babel and angular all have one based on [the Contributor Covenant v1](https://www.contributor-covenant.org/) so that might be a good one to consider

**Comment by ashaffer** [comment]
Personally i'm a fan of simplicity in these sorts of things. Complex rules have a way of growing ever more complex and taking on perverse meanings as people lobby and lawyer them. Something as simple as 'Be civil and inclusive'. Or even Postel's maxim, 'Be liberal in what you accept, and conservative in what you send' applied to discourse.

I think generally anything more complex than 'be civil and inclusive' tends to be more about the author's desire to write a manifesto than it is about actual governance.

EDIT: I should add I didn't intend that last line to be insulting. I love writing manifestos as much as the next person :p and would be happy to engage in it here. It's just that if the actual goal is governance of the projects, it may not be all that useful to do so.

**Comment by ghost** [comment]
I see a code of conduct as providing two things:

* communicating expected behavior to existing and new members
* setting up consequences ahead of time, before a problem arises

The worst time to debate what should happen when abuse crops up is after it happens, because then you have to deal with two issues at once.

The contributor covenant is pretty short and I think it provides more concrete ways of enumerating civility and inclusivity which otherwise may vary substantially between individuals.

https://www.contributor-covenant.org/version/1/4/code_of_conduct.txt

**Comment by jprichardson** [comment]
@substack just pick one that you like and I'm sure the rest will accept. The most important thing here is just making decisions and moving quickly, we can always change these things later. As far as I'm concerned and I'm sure most others, you're the BDFL here unless you choose someone else.

By the way, I'm glad to see you've chosen to go the org route :)

**Comment by ashaffer** [comment]
Ah, ya, I had written my comment before reading it. I like the text of the contributor covenant. I think that strikes the right balance of simplicity and specificity.

**Comment by ghost** [comment]
OK sounds good! I will add this to the browserify core repo and some of the other main ones.
