### ISSUE TITLE
Enable GitHub oAuth Access Restrictions

### ISSUE THREAD

**Issue by balupton** [browserify/discuss#11]
This feature is currently disabled:
https://help.github.com/articles/about-oauth-app-access-restrictions/

It can be enabled via:
https://github.com/organizations/browserify/settings/oauth_application_policy

I would do it myself, but it also eliminates SSH keys created before 2014 - of which I am not sure if any browserify infrastructure depends on.

**Comment by goto-bus-stop** [comment]
thanks for bringing this up. i think the appveyor CIs rely on this right now, not sure if there's anything else
