### ISSUE TITLE
Tidelift funds

### ISSUE THREAD

**Issue by feross** [browserify/discuss#12]
A company called Tidelift is selling OSS support to companies and funneling the funds to maintainers. They use the dependency trees of their customers to figure out which packages are depended upon and which, therefore, should get the funds. It's not a perfect metric, but I think they're trying to do the right thing.

The only work that maintainers have to do is commit to share release notes on the Tidelift site (I think they're going to automate this at some point), add a readme badge, and share info about security issues.

Wanted to make sure that folks here were aware of it.

Browserify has at least $417/mo available for the next two years
https://tidelift.com/lifter/search/npm/browserify

How does Tidelift pay maintainers?
https://tidelift.com/about/lifter

$1m to pay open source maintainers on Tidelift
https://blog.tidelift.com/1m-to-pay-open-source-maintainers-on-tidelift

**Comment by ghost** [comment]
If there is funding available, I think it's good to have an idea on what to spend those funds on. I can think of a few things:

* continuing maintenance on browserify core tools
* new plugins and transforms
* documentation and recipes
* performance work

I think the main website could use a redesign to emphasize some of the new work that's been done over the past few years and we could have a recipes section to show how to configure browserify with different combinations of other tools. Recipes for combinations of react, jsx, vue, typescript, angular, choo, gulp, grunt, npm scripts, budo, bankai, glslify, threejs, regl, or whatever else would be really nice to have.

**Comment by goto-bus-stop** [comment]
rad! i agree w @substack especially on documentation/recipes and performance work, where browserify can be lacking compared to other tools. personally i'd also really like to get Node-compatible ES modules in, with rollup-style scope hoisting optimization (either as a plugin or in core). i imagine the Modules WG will be stabilising at least some part of that over the next 2 years. there is also always more than enough work to do on core module shims, which have been evolving more rapidly in node.js in the past few years.

i'd love to pick some of this up, and have some time available to do so.

**Comment by goto-bus-stop** [comment]
I signed up. If someone else is also interested, I think you can just also sign up to lift the browserify package and tidelift will get in touch to work out how it gets split up and such.

**Comment by goto-bus-stop** [comment]
Tidelift messaged me about some more browserify-org packages that have small amounts of funding available each.

> Some of the eligible projects are:
>
> assert — $48/month
> resolve — $34/month
> vm-browserify — $28/month
> path-browserify — $19/month
> stream-browserify — $6/month
> timers-browserify — $4/month
> tty-browserify — $0.48/month

I'll sign up for the things I've worked on, if you the reader also contribute to any of these packages and are interested please message me or tidelift and we can work that out. (stream-browserify is more work than $6/month so we could pool funds from the main browserify repo for example)
