### ISSUE TITLE
crypto-browserify migration

### ISSUE THREAD

**Issue by bcomnes** [browserify/discuss#14]
Hey @dcousens, just noticing the movement of the crypto-browserify packages into this org. Whats the plan/what prompted the change? Perhaps I missed discussion elsewhere.

**Comment by dcousens** [comment]
Hi @bcomnes,

Fair question! I am tracking this in https://github.com/browserify/crypto-packages-ownership/issues/3

The packages in the https://github.com/crypto-browserify organization were falling behind in maintenance, with the existing maintainers (including myself for some) not having adequate time to allocate to them in recent years.

We have opted to move the packages to this organisation as they are fundamentally part of the same project anyway, in a hope to diversify the number of developers who can help maintain the ecosystem.

**Comment by dcousens** [comment]
I am happy to transfer the https://github.com/browserify/crypto-packages-ownership/issues/3 issue to this repository https://github.com/browserify/discuss/ after we have resolved the remaining `npm` ownership.

**Comment by bcomnes** [comment]
Cool, cool, sounds good. Just checking in.
