### ISSUE TITLE
migrate requirebin & wzrdin to org

### ISSUE THREAD

**Issue by ungoldman** [browserify/discuss#4]
https://wzrd.in (https://github.com/jfhbrook/wzrd.in) & http://requirebin.com (https://github.com/maxogden/requirebin) are two projects that have helped the browserify project a great deal. Both projects are also in need of new contributors and continuing maintenance and updates.

If @maxogden & @jfhbrook are interested, I think the browserify org would be a great place to house these two projects, bring attention to maintenance needs, recruit new contributors excited to lend a hand, and spread responsibility for maintenance to a larger group.

**Comment by jfhbrook** [comment]
I'm certainly open to it! I have no real attachment to the repo and where it lives.

As said in other places, we could really use a hand, especially in the code review and devops departments. If transferring these project to the org can help with that then I'm for it, though I'm not convinced that one follows from the other.

**Comment by jfhbrook** [comment]
wzrd.in is migrated. You'll have to ask Max about requirebin. I can do pubkeys for the ops stuff, though Max controls the DO account.

**Comment by ungoldman** [comment]
Thanks @jfhbrook!
